[package]
name = "gtk4-calculator"
version = "0.1.4"
edition = "2021"

[dependencies]
gtk = { version = "0.4.8", package="gtk4" }
gdk = { version = "0.4.8", package="gdk4" }
glib-macros = "0.15.11"
gio = "0.15.12"
gdk-pixbuf = "0.15.11"

