[package]
name = "gtk4-calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.4.8"
gdk4 = "0.4.8"
glib-macros = "0.15.11"
